services:
    kapowarr-react:
        container_name: kapowarr-react
        image: mrcas/kapowarr:latest # TODO: build packages on github
        volumes:
            - 'kapowarr-db:/app/db'
            - '/path/to/download_folder:/app/temp_downloads'
            - '/path/to/root_folder:/comics-1'
        ports:
            - 5656:5656
volumes:
    kapowarr-db:
