[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Kapowarr"
version = "2.0.0a1"
description = "Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">= 3.12"
dynamic = ["dependencies", "optional-dependencies"]

[project.scripts]
kapowarr = "kapowarr:main"

[tool.mypy]
python_version = "3.12"
pretty = true
warn_redundant_casts = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = [
  "libgencomics.*",
  "bencoding.*"
]
follow_untyped_imports = true

[tool.ruff]
target-version = "py312"
line-length = 88
lint.select = ["E", "F", "I", "U"]
lint.ignore = ["E501"]

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}

[tool.setuptools.dynamic.optional-dependencies]
dev = {file = "requirements-dev.txt"}

[tool.setuptools.package-data]
"backend.lib" = ["*"]
"frontend" = ["templates/*"]
"frontend.static" = ["css/*", "img/*", "js/*", "json/*"]
